### PR TITLE
The sulu-minimal project is English only. So no German text needed.

### PR DESCRIPTION
**Pull request by kfrohwein**

### CODE REVIEW

**Comment by alexander-schranz** [comment]
Hello @kfrohwein,

This is not correct as this locales are system locales and not content locales.

The correct way would be that this value should be available in all 4 system locales sulu/sulu supports (en, de, nl, fr). Maybe we should extend the base templates and webspace with all core locales currently @sulu/core-team?

**Comment by kfrohwein** [comment]
Hi,

sorry I don't get it.

The system is set up with

`  <localizations>
        <localization language="en" default="true"/>
    </localizations>`

So only English is active. Than I won't care about translating the menu to German. Okay if you want to add all languages... but with the current config I don't understand what you mean by "4 system locales" if it is not set?

**Comment by alexander-schranz** [comment]
@kfrohwein maybe I'm false but I think this value should be represented in the locale on the left bottom:

bildschirmfoto 2018-04-18 um 18 52 09

Or is the navigation context shown in the content locales language?

**Comment by kfrohwein** [comment]
The Interface is translated if I change the language in the language changer in your pic. That is correct. But the name of the navigation is bound to the content language switcher:

main-nav

main-nav-fr

**Comment by alexander-schranz** [comment]
@kfrohwein  For me this looks like a bug if I choose DE as system language (user locale) I would expect to see "Haupt Navigation" and not "Main navigation" independently which content locale is selected. In all other cases also system locale is used to render XML meta data.

/cc @chirimoya what do you think?

**Comment by kfrohwein** [comment]
@alexander-schranz But if I search the whole sulu-minimal project that string is only used in the example.com.xml. So imho this is a user space thing and belongs to content translation. By this it should not be translated if there is no other language set in the same file. But let's wait for @chirimoya

**Comment by danrot** [comment]
Since this is nothing being edited by a content manager, I would also consider that part of the system translation. So I would be with @alexander-schranz on that one.

**Comment by danrot** [comment]
Ah, that was by accident :see_no_evil: Can we still fix that correctly? :see_no_evil:

**Comment by danrot** [comment]
Reverted in 7f84b9f

**Comment by kfrohwein** [comment]
So that I understand this correctly:

Currently the Name of a Menu is set in the webspace XML. The value of the selectbox is changed by the content language selector.

You two suggest it should stay in the webspace XML but change if the system language changes. By this the Menu Names always have to be translated in all languages the UI can have.

imho I believe the menu even if configured in the webspace XML should be part of the site content and only be provided in the languages we edit the content. This is because if I want to add 5 different menus I would have to translate them in dutch and french even if my system is german and english only? Doesn't make sense to me. Even if menus are setup there they can completely differ from site to site.

**Comment by alexander-schranz** [comment]
@kfrohwein all static things should be shown in the language the user choose in its profile and not the content language of the page (see also the labels and info texts of the fields). Example you are a user with locale EN and you know that the site you edit need also be in the main navigation for Russia and Chinese so you should see this select in your user locale and not in the content locale. Also when you have webspace with 20 languages you don't translate navigations to all 20 only to the 4 user locales which exists in the backend.

**Pull request merged**
