### PR TITLE
Fixed using php internal webserver

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Related PRs | https://github.com/sulu/sulu/pull/4287
| License | MIT

#### What's in this PR?

Rename app.php to index.php

#### Why?

Fix using the php internal webserver. Which is at the beginning of symfony casts also used to first run a symfony project https://symfonycasts.com/screencast/symfony/setup. 

When we update the documentation we could remove the requirement to webserver bundle.

#### Example Usage

```bash
php -S 127.0.0.1:8000 -t public
```

### CODE REVIEW

**Comment by danrot** [comment]
The `/admin` URL isn't working for me not using the `WebServerBundle` this way.

**Comment by alexander-schranz** [comment]
@danrot as mentioned by you its because of the `/admin` folder. We should maybe rename the `/admin/build` folder to `/admin-build` to avoid problems for someone using the php internal webserver. /cc @chirimoya https://github.com/sulu/sulu/pull/4287

**Comment by danrot** [comment]
Is it just me, or is there something wrong with the delivered build?

**Comment by alexander-schranz** [comment]
@danrot rebuild done.

**Pull request merged**
