### PR TITLE
Fix exception controller of sulu for website

### PR DESCRIPTION
**Pull request by alexander-schranz**

### CODE REVIEW

**Comment by danrot** [comment]
Hm... That actually is only required because of a bug in the `FOSRestBundle`... (We should really do an update to 2.0...)

However, should we merge that? Might lead to confusion once we've udpated `FOSRestBundle`. If we merge it, I would at least add a comment, explaining that this is only temporary.

**Comment by c00n84** [comment]
@danrot we need it.

**Comment by alexander-schranz** [comment]
@c00n84 you just need to add the following to your website config:

app/config/website/config.yml

```yml
fos_rest:
    exception:
        enabled: false
```

this can be done directly in your project.

**Comment by alexander-schranz** [comment]
@danrot comment added

**Comment by alexander-schranz** [comment]
for FosRestBundle 2.0 you can remove the `exteption.enabled` and replace it with:

```yaml
fos_rest:
    zone:
        - { path: ^/admin/* }
```

**Pull request merged**
